name: "Build DASCore Docs"
description: "Builds DASCore's Documentation."

runs:
  using: "composite"
  steps:

    - uses: ./.github/actions/prep_doc_build

    - name: build quarto project
      shell: bash
      run: |
        python scripts/_doc_report.py time quarto_render -- \
          quarto render docs
