name: "Build DASCore Docs"
description: "Builds DASCore's Documentation."

runs:
  using: "composite"
  steps:

    - uses: ./.github/actions/prep_doc_build

    - name: build quarto project
      shell: bash -l {0}
      run: |
        quarto render docs
