name: "Build DASCore Docs"
description: "Builds DASCore's Documentation."

runs:
  using: "composite"
  steps:
    - name: Install quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: 1.3.450
        tinytex: true

    - name: print quarto version
      run: |
        quarto --version

    - name: render API docs
      shell: bash -l {0}
      run: |
        python scripts/build_api_docs.py
