exclude: scripts/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args: ['--fix=lf']
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-black
          - flake8-breakpoint
          - flake8-docstrings
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
#-   repo: https://github.com/pycqa/pydocstyle
#    rev: 6.1.1  # pick a git hash / tag to point to
#    hooks:
#      - id: pydocstyle
#        args:
#          - --ignore=D105,D106,D107,D200,D400,D203,D212
