name: dascore
channels:
  - conda-forge
  - defaults
dependencies:
  - pytest
  - pydantic
  - pip
  - pandas
  - pooch>=1.2
  - xarray
  - pre-commit
  - pytables
  - matplotlib
  - scipy
  - findiff
