# Note: The checkout action seems a bit flakey for also pulling tags. This
# action enables the checkout logic in one place.
name: "Checkout DASCore"
description: "Checkout the repo, ensuring tags are also pulled."

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: "true"
        fetch-depth: '0'

    - name: fetch tags
      shell: bash -l {0}
      run: |
        git fetch --tags --force
