"""
Tests for the panel guard in the tests scripts/generate_doc_code_tests.py writes.

A tutorial which prints a Patch, Spool or Inventory shows the reader the
text repr where the docs site could have drawn the panel. Nothing about
that is red: the page builds, the cell runs, and the only sign is output
nobody can fold. The guard turns it into a failing doc example, and
these tests are what say the guard is still installed.
"""

from __future__ import annotations

import builtins
import importlib.util
import os
import subprocess
import sys
import types
from pathlib import Path

import pandas as pd
import pytest

import dascore as dc

_REPO_ROOT = Path(__file__).resolve().parents[1]
_SCRIPT_PATH = _REPO_ROOT / "scripts" / "generate_doc_code_tests.py"
_QMD = "docs/tutorial/patch.qmd"

# The sdist ships tests but neither scripts/ nor docs/, on the same terms as
# test_build_notebooks.py skipping when scripts/ is absent.
pytestmark = pytest.mark.skipif(
    not _SCRIPT_PATH.is_file() or not (_REPO_ROOT / _QMD).is_file(),
    reason="scripts/ and docs/ are not installed",
)

# Run out of process, because the whole chain has to be exercised at once:
# the context installs the guard, and the generated module rebinds `print`
# from `builtins` after every chunk, which only reaches the guard because
# it reads the name then rather than at import. Out of process because
# `qmd_test_context` deliberately leaves `sys.stdout` reconfigured, and a
# doc example's harness should not follow the rest of the suite home.
_RUN_GENERATED = """
import builtins, importlib.util, sys, types
from pathlib import Path

root, printing = Path(sys.argv[1]), sys.argv[2] == "print"
spec = importlib.util.spec_from_file_location(
    "generate_doc_code_tests", root / "scripts" / "generate_doc_code_tests.py"
)
gen = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = gen
spec.loader.exec_module(gen)

# The generated conftest, under the name a generated module imports it by.
package = types.ModuleType("tests.test_autogenerated_doccode")
package.__path__ = []
conftest = types.ModuleType("tests.test_autogenerated_doccode.conftest")
conftest.__file__ = str(root / "tests" / "test_autogenerated_doccode" / "conftest.py")
exec(compile(gen.CONFTEST_MODULE, conftest.__file__, "exec"), conftest.__dict__)
sys.modules.update({
    "tests.test_autogenerated_doccode": package,
    "tests.test_autogenerated_doccode.conftest": conftest,
})

shown = "print(patch)" if printing else "patch"
source = gen.render_test_module(
    root / "docs" / "tutorial" / "patch.qmd",
    (
        gen.Chunk(1, "import dascore as dc\\npatch = dc.get_example_patch()\\n"),
        gen.Chunk(2, shown + "\\n"),
    ),
)
module = types.ModuleType("generated")
module.__file__ = str(root / "generated.py")
exec(compile(source, module.__file__, "exec"), module.__dict__)
module.test_main()
"""


def _load_generator():
    """Import the generator by path; scripts/ is not a package."""
    # Under a name of its own, not the script's: it has to go in
    # sys.modules for dataclasses to resolve its fields, and the script
    # is also imported under its own name by its tests beside it.
    spec = importlib.util.spec_from_file_location(
        "_doc_code_generator_under_test", _SCRIPT_PATH
    )
    module = importlib.util.module_from_spec(spec)
    # Registered before it is run: the script declares dataclasses, and
    # dataclasses resolves a field's annotation through sys.modules.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _run_generated(shown: str) -> subprocess.CompletedProcess:
    """Build and run a generated doc test whose second chunk shows a patch."""
    # Named on the path rather than left to the working directory, which
    # the harness changes to the qmd's own before running a chunk -- so a
    # bare cwd would hand the subprocess whatever dascore is installed
    # rather than the one this checkout is testing.
    env = dict(os.environ, PYTHONPATH=str(_REPO_ROOT))
    return subprocess.run(
        [sys.executable, "-c", _RUN_GENERATED, str(_REPO_ROOT), shown],
        capture_output=True,
        text=True,
        cwd=_REPO_ROOT,
        env=env,
        check=False,
    )


@pytest.fixture(scope="module")
def conftest_module():
    """The conftest the generator writes, run as a module.

    Executed from the template rather than imported from the generated
    tree, which is a build artifact and may not have been written yet.
    """
    generator = _load_generator()
    path = _REPO_ROOT / "tests" / "test_autogenerated_doccode" / "conftest.py"
    module = types.ModuleType("generated_doc_conftest")
    module.__file__ = str(path)
    exec(compile(generator.CONFTEST_MODULE, str(path), "exec"), module.__dict__)
    return module


@pytest.fixture(scope="module")
def panels(random_patch):
    """One of each kind of object which draws a panel."""
    return (random_patch, dc.spool(random_patch), dc.get_example_inventory())


class TestNoPrintedPanels:
    """Tests for the guard on its own."""

    def test_a_panel_may_not_be_printed(self, conftest_module, panels):
        """The whole point: printing a panel object fails the doc example.

        Over every kind, since the tutorials show three of them and a
        guard which knew only about patches would pass the other two.
        """
        for obj in panels:
            with conftest_module.no_printed_panels(_QMD):
                with pytest.raises(AssertionError) as info:
                    builtins.print(obj)  # noqa: T201
            # Named, because a doc example runs far from the qmd it came
            # from, and says what to do instead of printing.
            assert type(obj).__name__ in str(info.value)
            assert _QMD in str(info.value)
            assert "last expression" in str(info.value)

    def test_a_panel_may_not_be_printed_richly(self, conftest_module, random_patch):
        """
        The name a document binds is guarded too, not just the builtin.

        docs/tutorial/patch.qmd imports dascore's print, which is rich's,
        and that draws the text repr exactly as the builtin does.
        """
        with conftest_module.no_printed_panels(_QMD):
            # Inside the block on purpose: `from dascore import print` takes
            # the name once, so this is also what says the guard is in place
            # before a chunk gets to import it.
            from dascore import print as rich_print  # noqa: PLC0415

            with pytest.raises(AssertionError, match="Patch"):
                rich_print(random_patch)

    def test_anything_else_still_prints(self, conftest_module, capsys):
        """A guard which swallowed ordinary output would break every example."""
        with conftest_module.no_printed_panels(_QMD):
            builtins.print("a coordinate", 12)  # noqa: T201
        assert capsys.readouterr().out == "a coordinate 12\n"

    def test_a_frame_still_prints(self, conftest_module, random_patch):
        """
        What is refused is a dascore panel, not everything with an HTML repr.

        A DataFrame has one too, and the tutorials print several -- a
        guard which asked for `_repr_html_` rather than for the mixin
        would fail every one of them.
        """
        frame = dc.spool(random_patch).get_contents()
        with conftest_module.no_printed_panels(_QMD):
            builtins.print(frame)  # noqa: T201
        assert isinstance(frame, pd.DataFrame)

    def test_a_formatted_panel_goes_through(self, conftest_module, random_patch):
        """
        The limit, pinned: an object formatted first arrives as a string.

        `print(f"{patch}")` is what docs/recipes/parallelization.qmd
        writes inside a loop, and by the time the guard sees it there is
        nothing to tell it from any other text a document means to
        print. Stated here so the boundary is a decision rather than a
        gap somebody finds later.
        """
        with conftest_module.no_printed_panels(_QMD):
            builtins.print(f"{random_patch}")  # noqa: T201

    def test_printing_somewhere_else_goes_through(
        self, conftest_module, random_patch, tmp_path
    ):
        """
        A print with a `file` hides nothing: the cell shows no output at all.

        Which is what an example writing a repr to a file, or building
        one in a buffer to show afterwards, is doing.
        """
        path = tmp_path / "patch.txt"
        with conftest_module.no_printed_panels(_QMD), path.open("w") as handle:
            builtins.print(random_patch, file=handle)
        assert path.read_text() == f"{random_patch}\n"

    def test_both_names_are_put_back(self, conftest_module):
        """The guard belongs to the doc example, not to the session."""
        before = (builtins.print, dc.print)
        with conftest_module.no_printed_panels(_QMD):
            pass
        assert (builtins.print, dc.print) == before

    def test_both_names_are_put_back_after_a_failure(
        self, conftest_module, random_patch
    ):
        """Including after the failure the guard itself raises."""
        before = (builtins.print, dc.print)
        with pytest.raises(AssertionError):
            with conftest_module.no_printed_panels(_QMD):
                builtins.print(random_patch)  # noqa: T201
        assert (builtins.print, dc.print) == before


class TestAGeneratedTestRunsUnderTheGuard:
    """Tests the whole chain, from a generated module to the guard."""

    def test_a_printed_panel_fails_the_example(self):
        """
        Defining the guard and never reaching it is the silent failure.

        The generated module rebinds `print` from `builtins` after every
        chunk, so what puts a later chunk under the guard is that the
        rebinding reads the name while the guard is installed.
        """
        result = _run_generated("print")
        assert result.returncode != 0
        assert "draws" in result.stderr

    def test_showing_it_does_not(self):
        """The control: the same example, shown rather than printed."""
        result = _run_generated("show")
        assert result.returncode == 0, result.stderr
