name: "Load Shared Variables"
description: "Loads shared variables from .github/shared-vars.yml and sets them as environment variables"

runs:
  using: "composite"
  steps:
    - name: load shared variables
      shell: bash
      run: |
        # Read shared-vars.yml and set environment variables
        python << 'EOF'
        import yaml
        import os

        # Load shared variables file
        with open('.github/shared-vars.yml', 'r') as f:
            config = yaml.safe_load(f)

        # Set Python version environment variables
        python_config = config.get('python', {})

        env_vars = {
            'PYTHON_DEFAULT': python_config.get('default', '3.12'),
            'PYTHON_LATEST': python_config.get('latest', '3.13'),
            'PYTHON_RELEASE': python_config.get('release', '3.11'),
        }

        # Write to GITHUB_ENV
        with open(os.environ['GITHUB_ENV'], 'a') as env_file:
            for key, value in env_vars.items():
                env_file.write(f"{key}={value}\n")
                print(f"✅ Set {key}={value}")

        # For matrix values, we can't set them directly in env
        # Workflows will need to read the file directly for matrix strategy
        test_matrix = python_config.get('test_matrix', [])
        min_deps_matrix = python_config.get('min_deps_matrix', [])
        print(f"📋 Test matrix available: {test_matrix}")
        print(f"📋 Min deps matrix available: {min_deps_matrix}")
        EOF
