# This is where global configurations are added.

name: "Load Shared Variables"
description: "Loads shared variables and sets them as environment variables and outputs"

outputs:
  python-test-matrix:
    description: "Python version matrix for full tests"
    value: ${{ steps.load.outputs.python-test-matrix }}
  python-min-deps-matrix:
    description: "Python version matrix for minimum dependency tests"
    value: ${{ steps.load.outputs.python-min-deps-matrix }}

runs:
  using: "composite"
  steps:
    - name: load shared variables
      id: load
      shell: bash
      run: |
        {
          echo "PYTHON_DEFAULT=3.13"
          echo 'PYTHON_TEST_MATRIX=["3.11","3.12","3.13","3.14"]'
          echo 'PYTHON_MIN_DEPS_MATRIX=["3.13","3.14"]'
        } >> "$GITHUB_ENV"

        {
          echo 'python-test-matrix=["3.11","3.12","3.13","3.14"]'
          echo 'python-min-deps-matrix=["3.13","3.14"]'
        } >> "$GITHUB_OUTPUT"
