"""Generate inline pytest modules from executable Python snippets in qmd files.

This script mirrors hand-written documentation examples into
``tests/test_autogenerated_doccode`` so they run as part of the normal pytest
suite.

How it works:

1. Discover every source ``.qmd`` file under ``docs/``, excluding generated API
   docs under ``docs/api/``.
2. Parse each qmd file and keep only executable Quarto ``{python ...}`` fences.
3. Respect document-level ``execute.eval: false`` and chunk-level
   ``#| eval: false`` / ``#| execute: false`` switches.
4. Generate one pytest module per qmd file with a single ``test_main`` function.
5. Hoist any ``from __future__ import ...`` lines to module scope, then inline
   the remaining Python blocks into the generated test in original source
   order.
6. Insert a comment before each inlined block that points back to the qmd file
   and the first executable line of that block.
7. Write one generated ``conftest.py`` that provides the common execution
   context: run from the qmd directory, keep matplotlib non-interactive, and
   close figures after the test.

The generated tests are intentionally treated as build artifacts rather than
committed sources. Re-running this script rewrites the entire generated tree so
stale files disappear automatically.
"""

from __future__ import annotations

import argparse
import shlex
import shutil
import textwrap
from dataclasses import dataclass
from pathlib import Path
from textwrap import indent

# The generator always runs from the repository checkout.
REPO_ROOT = Path(__file__).resolve().parent.parent
# Source qmd files live under docs/.
DOCS_PATH = REPO_ROOT / "docs"
# Generated pytest files are mirrored into a dedicated test tree.
TESTS_PATH = REPO_ROOT / "tests" / "test_autogenerated_doccode"
# API docs are generated elsewhere and should not be mirrored again here.
API_DOCS_PATH = DOCS_PATH / "api"
# Force stable cross-platform text IO for both reads and writes.
TEXT_ENCODING = "utf-8"

# This template becomes one standalone pytest module per source qmd file.
AUTOGEN_HEADER = '''"""Autogenerated from {source_path}."""

{future_imports}import pytest
import builtins

from tests.test_autogenerated_doccode.conftest import qmd_test_context


@pytest.mark.docs_examples
def test_main():
    """Execute the python chunks from the source QMD."""
    # Keep `print` in module-global scope so one chunk can rebind it and later
    # chunks see the same shared runtime name before the per-chunk reset below.
    global print
    source_qmd = {source_path_literal}
    with qmd_test_context(source_qmd):
{body}
'''

# The generated conftest keeps reusable setup out of every generated module
# while still avoiding a bespoke runtime executor.
CONFTEST_MODULE = '''"""Shared helpers for autogenerated qmd tests."""

from __future__ import annotations

import os
from contextlib import contextmanager
from pathlib import Path
import sys

import matplotlib


@contextmanager
def qmd_test_context(source_qmd: str):
    """Run one autogenerated qmd test in the source document directory."""
    root = Path(__file__).resolve().parents[2]
    source_path = root / source_qmd
    old = Path.cwd()
    stdout = sys.stdout
    stderr = sys.stderr
    original_backend = matplotlib.get_backend()
    # Configure plotting lazily so importing the generated conftest does not
    # affect unrelated tests in the same process.
    matplotlib.use("Agg", force=True)
    import matplotlib.pyplot as plt
    from matplotlib.figure import Figure

    original_show = plt.show
    original_figure_show = Figure.show
    was_interactive = plt.isinteractive()
    try:
        # Windows CI often defaults to cp1252, which cannot print some of the
        # unicode characters used in DASCore's rich/text output.
        if hasattr(sys.stdout, "reconfigure"):
            sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        if hasattr(sys.stderr, "reconfigure"):
            sys.stderr.reconfigure(encoding="utf-8", errors="replace")
        plt.ioff()
        plt.show = lambda *args, **kwargs: None
        Figure.show = lambda self, *args, **kwargs: None
        os.chdir(source_path.parent)
        yield
    finally:
        os.chdir(old)
        sys.stdout = stdout
        sys.stderr = stderr
        plt.show = original_show
        Figure.show = original_figure_show
        if was_interactive:
            plt.ion()
        else:
            plt.ioff()
        # Always close figures so one doc example cannot leak state to another.
        plt.close("all")
        if matplotlib.get_backend() != original_backend:
            matplotlib.use(original_backend, force=True)
'''


@dataclass(frozen=True)
class Chunk:
    """A chunk extracted from a qmd file."""

    # First executable line inside the qmd code fence.
    start_line: int
    # The literal Python source that will be compiled and executed.
    source: str


@dataclass(frozen=True)
class QmdFile:
    """The executable content extracted from a qmd file."""

    # Source qmd path on disk.
    path: Path
    # All executable python chunks found in the document.
    chunks: tuple[Chunk, ...]


def _parse_bool(value: str) -> bool | None:
    """Parse a yaml-like bool."""
    # Front matter and chunk options use yaml-like booleans.
    cleaned = value.strip().strip("'\"").lower()
    if cleaned in {"true", "yes", "1"}:
        return True
    if cleaned in {"false", "no", "0"}:
        return False
    return None


def _split_front_matter(lines: list[str]) -> tuple[list[str], list[str]]:
    """Split a qmd file into front matter and body lines."""
    # Only treat a leading --- block as front matter.
    if not lines or lines[0].strip() != "---":
        return [], lines
    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            return lines[1:index], lines[index + 1 :]
    return [], lines


def _parse_doc_eval(front_matter: list[str]) -> bool:
    """Return the document-level eval flag."""
    # Quarto can disable execution for the entire document with:
    # execute:
    #   eval: false
    in_execute = False
    execute_indent = 0
    for line in front_matter:
        stripped = line.strip()
        # Ignore blank lines and front-matter comments.
        if not stripped or stripped.startswith("#"):
            continue
        indent_size = len(line) - len(line.lstrip(" "))
        if stripped.startswith("execute:"):
            # Track when we are inside the execute: subsection.
            in_execute = True
            execute_indent = indent_size
            remainder = stripped.partition(":")[2].strip()
            if remainder:
                parsed = _parse_bool(remainder)
                if parsed is not None:
                    return parsed
            continue
        if in_execute and indent_size <= execute_indent:
            in_execute = False
        if in_execute and ":" in stripped:
            key, _, value = stripped.partition(":")
            if key.strip() == "eval":
                parsed = _parse_bool(value)
                if parsed is not None:
                    return parsed
    return True


def _parse_fence_header(spec: str) -> tuple[str | None, dict[str, str]]:
    """Parse a Quarto fence header into language and key/value options."""
    # The raw fence spec arrives like "{python}" or
    # "{python filename="example.py"}".
    cleaned = spec.strip()
    if not cleaned.startswith("{") or not cleaned.endswith("}"):
        return None, {}
    inner = cleaned[1:-1].strip()
    if not inner:
        return None, {}
    # Accept either comma-delimited or space-delimited Quarto options while
    # preserving quoted values like filename="example file.py".
    tokens = shlex.split(inner.replace(",", " "))
    if not tokens:
        return None, {}
    language = tokens[0].strip()
    options: dict[str, str] = {}
    for token in tokens[1:]:
        if "=" not in token:
            continue
        key, _, value = token.partition("=")
        options[key.strip()] = value.strip()
    return language, options


def _is_python_fence(spec: str) -> bool:
    """Return True if the fence should execute as python."""
    language, options = _parse_fence_header(spec)
    # Plain markdown-style {.python} fences are not Quarto executable cells.
    if language is None or language.startswith("."):
        return False
    for key in ("eval", "execute"):
        parsed = _parse_bool(options.get(key, ""))
        if parsed is False:
            return False
    return language == "python"


def _chunk_is_executable(chunk_lines: list[str]) -> bool:
    """Return True if a chunk should be executed."""
    # Chunk-local `#| eval: false` or `#| execute: false` overrides the
    # document-level default.
    for line in chunk_lines:
        stripped = line.strip()
        if not stripped.startswith("#|") or ":" not in stripped:
            continue
        option = stripped[2:].strip()
        key, _, value = option.partition(":")
        parsed = _parse_bool(value)
        if parsed is None:
            continue
        if key.strip() in {"eval", "execute"} and parsed is False:
            return False
    return True


def extract_qmd_file(path: Path) -> QmdFile:
    """Extract executable python chunks from a qmd file."""
    # Read with explicit UTF-8 so Windows does not fall back to cp1252.
    lines = path.read_text(encoding=TEXT_ENCODING).splitlines()
    front_matter, body = _split_front_matter(lines)
    # Skip the whole document if execution is disabled in front matter.
    if not _parse_doc_eval(front_matter):
        return QmdFile(path=path, chunks=())

    chunks: list[Chunk] = []
    in_chunk = False
    chunk_lines: list[str] = []
    chunk_start = 0
    should_capture = False

    # `body` excludes front matter, but we still want source comments to point
    # back to original qmd line numbers.
    body_start_line = len(front_matter) + 1 if front_matter else 0
    for offset, line in enumerate(body, start=body_start_line + 1):
        stripped = line.strip()
        # Opening fence: decide whether this cell is executable python.
        if not in_chunk and stripped.startswith("```{"):
            in_chunk = True
            should_capture = _is_python_fence(stripped[3:])
            chunk_lines = []
            # Record the first executable line inside the fence, not the fence
            # header itself, so the generated source comment points at code.
            chunk_start = offset + 1
            continue
        # Closing fence: finalize the captured chunk if it should execute.
        if in_chunk and stripped == "```":
            if should_capture and _chunk_is_executable(chunk_lines):
                # Preserve the chunk as a single executable unit so variables
                # defined earlier in the block remain available later.
                source = textwrap.dedent("\n".join(chunk_lines)).strip()
                if source:
                    chunks.append(Chunk(start_line=chunk_start, source=source + "\n"))
            in_chunk = False
            should_capture = False
            chunk_lines = []
            continue
        # Any non-fence line inside the current chunk is part of the source.
        if in_chunk:
            chunk_lines.append(line)
    return QmdFile(path=path, chunks=tuple(chunks))


def iter_source_qmd_files(base_path: Path = DOCS_PATH) -> list[Path]:
    """Return source qmd files to mirror into tests."""
    # Mirror every qmd under docs/, except generated API docs.
    return [
        path
        for path in sorted(base_path.rglob("*.qmd"))
        if API_DOCS_PATH not in path.parents and path != API_DOCS_PATH
    ]


def get_output_path(source_path: Path, tests_path: Path = TESTS_PATH) -> Path:
    """Map a qmd file to its generated pytest module."""
    # Keep the generated tree shaped like docs/, but swap the filename to
    # `test_<stem>.py` so pytest discovers it naturally.
    relative = source_path.relative_to(DOCS_PATH)
    filename = f"test_{source_path.stem}.py"
    if len(relative.parts) == 1:
        return tests_path / filename
    return tests_path.joinpath(*relative.parts[:-1], filename)


def _render_chunk_comment(source_path: str, start_line: int) -> str:
    """Render the source-location comment for one inlined chunk."""
    return f"### {source_path}:{start_line}"


def _split_future_imports(source: str) -> tuple[list[str], list[str]]:
    """Split future imports from the rest of one chunk."""
    future_imports: list[str] = []
    body_lines: list[str] = []
    for line in source.splitlines():
        stripped = line.strip()
        if stripped.startswith("from __future__ import "):
            future_imports.append(stripped)
            continue
        body_lines.append(line)
    return future_imports, body_lines


def _collect_future_imports(
    chunks: tuple[Chunk, ...],
) -> tuple[tuple[str, ...], tuple[Chunk, ...]]:
    """Hoist and deduplicate future imports across all chunks."""
    seen: set[str] = set()
    future_imports: list[str] = []
    cleaned_chunks: list[Chunk] = []
    for chunk in chunks:
        chunk_future_imports, body_lines = _split_future_imports(chunk.source)
        for future_import in chunk_future_imports:
            if future_import not in seen:
                seen.add(future_import)
                future_imports.append(future_import)
        body_source = "\n".join(body_lines).strip()
        if body_source:
            cleaned_chunks.append(
                Chunk(start_line=chunk.start_line, source=body_source + "\n")
            )
    return tuple(future_imports), tuple(cleaned_chunks)


def _render_chunk_source(source_path: str, chunk: Chunk) -> str:
    """Render one chunk as plain inline test code."""
    # Keep the qmd source location visible right above the pasted code block.
    chunk_block = (
        f"{_render_chunk_comment(source_path, chunk.start_line)}\n"
        f"{chunk.source.rstrip()}\n\n"
        # Reset `print` after each chunk so one example's reassignment does not
        # leak into later chunks in the same generated test module.
        "print = builtins.print"
    )
    # Indent so the emitted code lives inside `with qmd_test_context(...):`.
    return indent(chunk_block.rstrip(), " " * 8)


def render_test_module(source_path: Path, chunks: tuple[Chunk, ...]) -> str:
    """Render a generated pytest module."""
    # Normalize to forward slashes so generated modules are stable across
    # platforms and Windows paths do not introduce escape sequences.
    relative_source_path = source_path.relative_to(REPO_ROOT).as_posix()
    # Future imports must appear at module scope, so hoist them before inlining
    # the remaining chunk bodies into the test function.
    future_imports, cleaned_chunks = _collect_future_imports(chunks)
    future_import_block = ""
    if future_imports:
        future_import_block = "\n".join(future_imports) + "\n\n"
    # Emit chunks directly into the test body so the generated file is readable
    # without reconstructing execution from a serialized tuple payload.
    body = "\n\n".join(
        _render_chunk_source(relative_source_path, chunk) for chunk in cleaned_chunks
    )
    if not body:
        body = "        pass"
    return AUTOGEN_HEADER.format(
        source_path=relative_source_path,
        future_imports=future_import_block,
        source_path_literal=repr(relative_source_path),
        body=body,
    )


def write_test_tree(
    qmd_files: list[QmdFile],
    tests_path: Path = TESTS_PATH,
) -> list[Path]:
    """Rewrite the generated qmd test tree."""
    # Regeneration is full-rewrite rather than incremental so stale tests
    # disappear automatically when docs are removed or stop containing code.
    if tests_path.exists():
        try:
            shutil.rmtree(tests_path)
        except OSError as e:
            print(  # noqa: T201
                f"Failed to remove generated test tree at {tests_path}: {e}"
            )
            raise
    # Seed the package root and generated conftest first.
    tests_path.mkdir(parents=True)
    (tests_path / "__init__.py").write_text("", encoding=TEXT_ENCODING)
    conftest_path = tests_path / "conftest.py"
    conftest_path.write_text(CONFTEST_MODULE, encoding=TEXT_ENCODING)

    written = {tests_path / "__init__.py", conftest_path}
    for qmd_file in qmd_files:
        # Skip documents that contain no executable python cells.
        if not qmd_file.chunks:
            continue
        output_path = get_output_path(qmd_file.path, tests_path=tests_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        current = output_path.parent
        # Ensure nested generated tests remain importable as pytest packages.
        while current != tests_path:
            init_path = current / "__init__.py"
            if not init_path.exists():
                init_path.write_text("", encoding=TEXT_ENCODING)
            written.add(init_path)
            current = current.parent
        # Write the generated pytest module for this one source document.
        output_path.write_text(
            render_test_module(qmd_file.path, qmd_file.chunks),
            encoding=TEXT_ENCODING,
        )
        written.add(output_path)
    return sorted(written)


def generate_doc_code_tests() -> list[Path]:
    """Generate the qmd-backed test tree."""
    # Extract all source docs first, then mirror only the executable ones.
    qmd_files = [extract_qmd_file(path) for path in iter_source_qmd_files()]
    return write_test_tree(qmd_files)


def main() -> int:
    """Generate qmd-backed tests from docs sources."""
    # The CLI is intentionally simple today, but argparse gives us a stable
    # entrypoint if we need options later.
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    written = generate_doc_code_tests()
    rel_path = TESTS_PATH.relative_to(REPO_ROOT)
    print(f"Generated {len(written)} files in {rel_path}")  # noqa: T201
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
