"""Generate pytest modules from executable python snippets in qmd files."""

from __future__ import annotations

import argparse
import shutil
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_PATH = REPO_ROOT / "docs"
TESTS_PATH = REPO_ROOT / "tests" / "test_autogenerated_doccode"
API_DOCS_PATH = DOCS_PATH / "api"
TEXT_ENCODING = "utf-8"

AUTOGEN_HEADER = """\"\"\"Autogenerated from {source_path}.\"\"\"

from __future__ import annotations

import pytest

from tests.test_autogenerated_doccode._runtime import run_qmd_chunks

SOURCE_QMD = {source_path_literal}
CHUNKS = {chunks_literal}


@pytest.mark.docs_examples
def test_qmd_examples():
    \"\"\"Execute the python chunks from the source QMD.\"\"\"
    run_qmd_chunks(SOURCE_QMD, CHUNKS)
"""

RUNTIME_MODULE = '''"""Helpers for generated qmd tests."""

from __future__ import annotations

import os
from contextlib import contextmanager
from pathlib import Path

import matplotlib

matplotlib.use("Agg", force=True)
import matplotlib.pyplot as plt
from matplotlib.figure import Figure

plt.ioff()
plt.show = lambda *args, **kwargs: None
Figure.show = lambda self, *args, **kwargs: None


@contextmanager
def _pushd(path: Path):
    """Temporarily change the working directory."""
    old = Path.cwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(old)


def run_qmd_chunks(source_qmd: str, chunks: tuple[tuple[int, str], ...]) -> None:
    """Execute the chunks for a qmd-backed generated test."""
    root = Path(__file__).resolve().parents[2]
    source_path = root / source_qmd
    namespace = {"__name__": "__qmd_test__"}
    try:
        with _pushd(source_path.parent):
            for start_line, source in chunks:
                code = compile(source, f"{source_qmd}:{start_line}", "exec")
                exec(code, namespace, namespace)
    finally:
        plt.close("all")
'''


@dataclass(frozen=True)
class Chunk:
    """A chunk extracted from a qmd file."""

    start_line: int
    source: str


@dataclass(frozen=True)
class QmdFile:
    """The executable content extracted from a qmd file."""

    path: Path
    chunks: tuple[Chunk, ...]


def _parse_bool(value: str) -> bool | None:
    """Parse a yaml-like bool."""
    cleaned = value.strip().strip("'\"").lower()
    if cleaned == "true":
        return True
    if cleaned == "false":
        return False
    return None


def _split_front_matter(lines: list[str]) -> tuple[list[str], list[str]]:
    """Split a qmd file into front matter and body lines."""
    if not lines or lines[0].strip() != "---":
        return [], lines
    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            return lines[1:index], lines[index + 1 :]
    return [], lines


def _parse_doc_eval(front_matter: list[str]) -> bool:
    """Return the document-level eval flag."""
    in_execute = False
    execute_indent = 0
    for line in front_matter:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        indent = len(line) - len(line.lstrip(" "))
        if stripped.startswith("execute:"):
            in_execute = True
            execute_indent = indent
            remainder = stripped.partition(":")[2].strip()
            if remainder:
                parsed = _parse_bool(remainder)
                if parsed is not None:
                    return parsed
            continue
        if in_execute and indent <= execute_indent:
            in_execute = False
        if in_execute and ":" in stripped:
            key, _, value = stripped.partition(":")
            if key.strip() == "eval":
                parsed = _parse_bool(value)
                if parsed is not None:
                    return parsed
    return True


def _is_python_fence(spec: str) -> bool:
    """Return True if the fence should execute as python."""
    cleaned = spec.strip()
    if not cleaned.startswith("{") or cleaned.startswith("{.python"):
        return False
    inner = cleaned[1:-1].strip()
    if not inner:
        return False
    language = inner.split(",", 1)[0].split(None, 1)[0].strip()
    return language == "python"


def _chunk_is_executable(chunk_lines: list[str]) -> bool:
    """Return True if a chunk should be executed."""
    for line in chunk_lines:
        stripped = line.strip()
        if not stripped.startswith("#|") or ":" not in stripped:
            continue
        option = stripped[2:].strip()
        key, _, value = option.partition(":")
        parsed = _parse_bool(value)
        if parsed is None:
            continue
        if key.strip() in {"eval", "execute"} and parsed is False:
            return False
    return True


def extract_qmd_file(path: Path) -> QmdFile:
    """Extract executable python chunks from a qmd file."""
    lines = path.read_text(encoding=TEXT_ENCODING).splitlines()
    front_matter, body = _split_front_matter(lines)
    if not _parse_doc_eval(front_matter):
        return QmdFile(path=path, chunks=())

    chunks: list[Chunk] = []
    in_chunk = False
    chunk_lines: list[str] = []
    chunk_start = 0
    should_capture = False

    body_start_line = len(front_matter) + 1 if front_matter else 0
    for offset, line in enumerate(body, start=body_start_line + 1):
        stripped = line.strip()
        if not in_chunk and stripped.startswith("```{"):
            in_chunk = True
            should_capture = _is_python_fence(stripped[3:])
            chunk_lines = []
            chunk_start = offset + 1
            continue
        if in_chunk and stripped == "```":
            if should_capture and _chunk_is_executable(chunk_lines):
                source = "\n".join(chunk_lines).strip()
                if source:
                    chunks.append(Chunk(start_line=chunk_start, source=source + "\n"))
            in_chunk = False
            should_capture = False
            chunk_lines = []
            continue
        if in_chunk:
            chunk_lines.append(line)
    return QmdFile(path=path, chunks=tuple(chunks))


def iter_source_qmd_files(base_path: Path = DOCS_PATH) -> list[Path]:
    """Return source qmd files to mirror into tests."""
    return [
        path
        for path in sorted(base_path.rglob("*.qmd"))
        if API_DOCS_PATH not in path.parents and path != API_DOCS_PATH
    ]


def get_output_path(source_path: Path, tests_path: Path = TESTS_PATH) -> Path:
    """Map a qmd file to its generated pytest module."""
    relative = source_path.relative_to(DOCS_PATH)
    filename = f"test_{source_path.stem}.py"
    if len(relative.parts) == 1:
        return tests_path / filename
    return tests_path.joinpath(*relative.parts[:-1], filename)


def render_test_module(source_path: Path, chunks: tuple[Chunk, ...]) -> str:
    """Render a generated pytest module."""
    chunk_payload = tuple((chunk.start_line, chunk.source) for chunk in chunks)
    return AUTOGEN_HEADER.format(
        source_path=source_path.relative_to(REPO_ROOT),
        source_path_literal=repr(source_path.relative_to(REPO_ROOT).as_posix()),
        chunks_literal=repr(chunk_payload),
    )


def write_test_tree(
    qmd_files: list[QmdFile],
    tests_path: Path = TESTS_PATH,
) -> list[Path]:
    """Rewrite the generated qmd test tree."""
    if tests_path.exists():
        try:
            shutil.rmtree(tests_path)
        except Exception as e:
            print(  # noqa: T201
                f"Failed to remove generated test tree at {tests_path}: {e}"
            )
            raise
    tests_path.mkdir(parents=True)
    (tests_path / "__init__.py").write_text("", encoding=TEXT_ENCODING)
    runtime_path = tests_path / "_runtime.py"
    runtime_path.write_text(RUNTIME_MODULE, encoding=TEXT_ENCODING)

    written = {tests_path / "__init__.py", runtime_path}
    for qmd_file in qmd_files:
        if not qmd_file.chunks:
            continue
        output_path = get_output_path(qmd_file.path, tests_path=tests_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        current = output_path.parent
        while current != tests_path:
            init_path = current / "__init__.py"
            if not init_path.exists():
                init_path.write_text("", encoding=TEXT_ENCODING)
            written.add(init_path)
            current = current.parent
        output_path.write_text(
            render_test_module(qmd_file.path, qmd_file.chunks),
            encoding=TEXT_ENCODING,
        )
        written.add(output_path)
    return sorted(written)


def generate_autogenerated_doccode_tests() -> list[Path]:
    """Generate the qmd-backed test tree."""
    qmd_files = [extract_qmd_file(path) for path in iter_source_qmd_files()]
    return write_test_tree(qmd_files)


def main() -> int:
    """Generate qmd-backed tests from docs sources."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    written = generate_autogenerated_doccode_tests()
    rel_path = TESTS_PATH.relative_to(REPO_ROOT)
    print(f"Generated {len(written)} files in {rel_path}")  # noqa: T201
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
