"""Tests for generating autogenerated doccode pytest modules."""

from __future__ import annotations

from pathlib import Path

from generate_autogenerated_doccode_tests import (
    DOCS_PATH,
    REPO_ROOT,
    TEXT_ENCODING,
    Chunk,
    QmdFile,
    extract_qmd_file,
    get_output_path,
    render_test_module,
    write_test_tree,
)


def _write(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding=TEXT_ENCODING)
    return path


class TestExtractQmdFile:
    """Tests for extracting executable qmd chunks."""

    def test_skips_plain_python_fences(self, tmp_path):
        """Only executable quarto python fences should be included."""
        path = _write(
            tmp_path / "example.qmd",
            """---
title: Example
---

```{python}
import dascore as dc
```

```{.python}
print("not executed")
```
""",
        )
        out = extract_qmd_file(path)
        assert out.chunks == (Chunk(start_line=5, source="import dascore as dc\n"),)

    def test_skips_doc_with_eval_false(self, tmp_path):
        """Document-level eval false should skip all chunks."""
        path = _write(
            tmp_path / "example.qmd",
            """---
execute:
  eval: false
---

```{python}
print("nope")
```
""",
        )
        assert extract_qmd_file(path).chunks == ()

    def test_extracts_python_fence_with_space_delimited_options(self, tmp_path):
        """Quarto python fences can include filename options after a space."""
        path = _write(
            tmp_path / "example.qmd",
            """```{python filename="example.py"}
print("run")
```
""",
        )
        out = extract_qmd_file(path)
        assert out.chunks == (Chunk(start_line=2, source='print("run")\n'),)

    def test_reads_qmd_with_utf8_encoding(self, tmp_path, monkeypatch):
        """Extraction should force UTF-8 instead of platform default encodings."""
        path = _write(tmp_path / "example.qmd", "placeholder")
        called: dict[str, str | None] = {}
        original = Path.read_text

        def _read_text(self, *args, **kwargs):
            if self == path:
                called["encoding"] = kwargs.get("encoding")
                return """```{python}
print("run")
```"""
            return original(self, *args, **kwargs)

        monkeypatch.setattr(Path, "read_text", _read_text)

        out = extract_qmd_file(path)

        assert called["encoding"] == TEXT_ENCODING
        assert out.chunks == (Chunk(start_line=2, source='print("run")\n'),)

    def test_skips_chunk_with_eval_or_execute_false(self, tmp_path):
        """Chunk-level execution flags should be honored."""
        path = _write(
            tmp_path / "example.qmd",
            """```{python}
#| eval: false
print("skip")
```

```{python}
#| execute: false
print("skip")
```

```{python}
print("run")
```
""",
        )
        out = extract_qmd_file(path)
        assert out.chunks == (Chunk(start_line=12, source='print("run")\n'),)


class TestOutputPaths:
    """Tests for source-to-test path mapping."""

    def test_root_doc_maps_to_root_test(self):
        """Top-level docs should stay at the top of autogenerated tests."""
        source = DOCS_PATH / "index.qmd"
        tests = Path("/repo/tests/test_autogenerated_doccode")
        assert get_output_path(source, tests_path=tests) == tests / "test_index.py"

    def test_nested_doc_maps_to_nested_test(self):
        """Nested docs should keep their relative directory structure."""
        source = DOCS_PATH / "tutorial" / "file_io.qmd"
        tests = Path("/repo/tests/test_autogenerated_doccode")
        expected = tests / "tutorial" / "test_file_io.py"
        assert get_output_path(source, tests_path=tests) == expected


class TestRenderAndWrite:
    """Tests for generated module output."""

    def test_render_includes_source_and_chunk_payload(self):
        """Generated modules should point back to the source qmd."""
        source = REPO_ROOT / "docs" / "tutorial" / "example.qmd"
        module = render_test_module(source, (Chunk(start_line=12, source="x = 1\n"),))
        assert "Autogenerated from docs/tutorial/example.qmd" in module
        assert "@pytest.mark.docs_examples" in module
        assert "SOURCE_QMD = 'docs/tutorial/example.qmd'" in module
        assert "CHUNKS = ((12, 'x = 1\\n'),)" in module

    def test_write_tree_removes_stale_files(self, tmp_path):
        """Regeneration should replace the whole generated test tree."""
        tests_path = tmp_path / "tests" / "test_autogenerated_doccode"
        stale = tests_path / "obsolete.py"
        stale.parent.mkdir(parents=True)
        stale.write_text("old")

        source = DOCS_PATH / "tutorial" / "file_io.qmd"
        chunks = (Chunk(start_line=1, source="print(1)\n"),)
        qmd_file = QmdFile(path=source, chunks=chunks)

        written = write_test_tree([qmd_file], tests_path=tests_path)
        output = tests_path / "tutorial" / "test_file_io.py"

        assert output in written
        assert output.exists()
        assert not stale.exists()
        assert (tests_path / "_runtime.py").exists()
