# This action renders and publishes the development docs whenever
# new commits are added to the master or dev branch.

name: BuildDeployDevDocs

on:
  # Runs on pushes targeting the development branches
  push:
    branches: ["master", "dev"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  deployments: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: "true"
          fetch-depth: '0'

      - uses: ./.github/actions/load-shared-vars

      - uses: ./.github/actions/mamba-install-dascore
        with:
          # Defined in .github/actions/load-shared-vars/action.yml
          python-version: ${{ env.PYTHON_DEFAULT }}
          environment-file: './.github/doc_environment.yml'
          prepare-test-data: "true"

      - uses: ./.github/actions/prep_doc_build

      - name: publish docs to netlify
        shell: bash -l {0}
        env:
          QUARTO_PRINT_STACK: true
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
            quarto publish docs --no-prompt --no-browser
