# This action renders and publishes the development docs whenever
# new commits are added to the master bracnh.

name: BuildDeployDevDocs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  deployments: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          python-version: "3.10"
          activate-environment: dascore
          environment-file: environment.yml
          condarc-file: .github/test_condarc.yml

      - name: install dascore with docbuild reqs
        shell: bash -l {0}
        run: |
          conda install -c conda-forge pandoc
          python -m pip install -e .[docs]

      - name: Install quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.2.335
          tinytex: true

      - name: print quarto version
        run: |
          quarto --version

      - name: Render Quarto Project
        shell: bash -l {0}
        run: |
          python scripts/build_api_docs.py

      - name: Publish Quarto
        shell: bash -l {0}
        env:
          QUARTO_PRINT_STACK: true
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}
        run: |
            quarto publish docs --no-prompt --no-browser
