# Create documentation for stable (latest version) and deploy
name: BuildDeployStableDocs

on:
  # Runs when creating a new release
  release:
    types: [ created ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  deployments: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout

      - uses: ./.github/actions/mamba-install-dascore
        with:
          python-version: "3.12"
          environment-file: './.github/doc_environment.yml'

      - uses: ./.github/actions/build-docs

      #      - name: Setup Pages
      #        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/_site'

      - name: Zip doc build
        if: startsWith(github.ref, 'refs/tags/')
        run: zip docs.zip docs/_site -r

      - name: Upload release docs
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: docs.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
