name: Label PRs

on:
  pull_request_target:

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4 # pulls the PR code
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
