# Upload to PyPI when a new release tag is made.
name: PublishPackage
on:
  release:
    types:
      - published

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "get tags"
        run: |
          git fetch --tags --force # Retrieve annotated tags.

      - name: setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          environment-file: environment.yml
          python-version: 3.11

      - name: create dists
        shell: bash -l {0}
        run: |
          python -m pip install build
          python -m build

      - name: publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
