---
title: Transformations
execute:
  warning: false
---

In DASCore, transformations are operations which change the units of a patch. Transforms can be found in the [transform module](`dascore.transform`) or access as `Patch` methods.

# Discrete Fourier Transforms

The [Discrete Fourier Transform](https://en.wikipedia.org/wiki/Discrete_Fourier_transform) (dft) is commonly used in many signal processing workflows. DASCore implements this as the [dft](`dascore.transform.fourier.dft`) patch method.

```{python}
import numpy as np
import dascore as dc

# Get example patch, set unit to velocity (for demonstration)
patch = dc.get_example_patch().set_units("m/s")

transformed = patch.dft(dim="time")

# Note how the dimension name has changed
print(f"old_dims: {patch.dims} new dims: {transformed.dims}")

# As have the units
old_units = patch.attrs.data_units
new_units = transformed.attrs.data_units
print(f"old units: {old_units}, new units: {new_units}")
```

:::{.callout-note}
The transformed dimension names change; "time" becomes "ft_time" indicating the domain of the dimension has changed. The units are also updated. See the [note on Fourier transforms in DASCore](../notes/dft_notes.qmd) for more details.
:::

In many cases, it is advantageous to only calculate the fourier transform corresponding to the positive frequencies (since the Fourier transform of a real signal is symmetric).

```{python}
# Transform distance axis to Fourier domain using real fourier transform
real_transform = patch.dft(dim='distance', real=True)
print(real_transform.get_coord("ft_distance"))
```

The Inverse Discrete Fourier Transform [idft](`dascore.transform.fourier.idft`) undoes the transformation.

```{python}
# Transform distance axis to Fourier domain using real fourier transform
real_transform = patch.dft(dim='distance', real=True)
print(real_transform.get_coord("ft_distance"))
```

# Short Time Fourier Transform

Related to the Discrete Fourier Transform, the [Short Term Fourier Transform](https://en.wikipedia.org/wiki/Short-time_Fourier_transform) is useful for analyzing the time-dependent frequency content. DASCore implements this as [stft](`dascore.transform.fourier.stft`) and the corresponding [istft](`dascore.transform.fourier.istft`).

```{python}
import numpy as np
import dascore as dc
from dascore.units import second, percent

# Get example patch, set unit to velocity (for demonstration)
patch = (
    dc.get_example_patch("chirp", channel_count=3)
    .set_units("m/s")
)

patch.viz.waterfall(scale=0.1)
```

```{python}
# Perform the transform, visualize the amplitude spectra, for the first
# channel then invert.
transformed = (
    patch.stft(time=1*second, overlap=50*percent)
)
inverse =  transformed.istft()

transformed.abs().select(distance=0, samples=True).squeeze().viz.waterfall()
```
